"""users table picture_path nullable false

Revision ID: 0fc2f0fe7e7d
Revises: 50ed4043e1e4
Create Date: 2026-01-20 09:59:50.712364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc2f0fe7e7d'
down_revision: Union[str, Sequence[str], None] = '50ed4043e1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'picture_path',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'picture_path',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
