"""create tables

Revision ID: 142fbe0b6056
Revises: 
Create Date: 2026-02-08 21:01:29.199010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '142fbe0b6056'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_actions',
    sa.Column('app_action_id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), nullable=False),
    sa.Column('rank', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('app_action_id')
    )
    op.create_table('app_modules',
    sa.Column('app_module_id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), nullable=False),
    sa.Column('rank', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('app_module_id')
    )
    op.create_table('form_types',
    sa.Column('form_type_id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('form_type_id')
    )
    op.create_table('offices',
    sa.Column('office_id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('office_id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('user_types',
    sa.Column('user_type_id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('is_editable', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('user_type_id')
    )
    op.create_table('app_module_actions',
    sa.Column('app_module_action_id', sa.INTEGER(), nullable=False),
    sa.Column('app_module_id', sa.SMALLINT(), nullable=False),
    sa.Column('app_action_id', sa.SMALLINT(), nullable=False),
    sa.ForeignKeyConstraint(['app_action_id'], ['app_actions.app_action_id'], ),
    sa.ForeignKeyConstraint(['app_module_id'], ['app_modules.app_module_id'], ),
    sa.PrimaryKeyConstraint('app_module_action_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_type_id', sa.SMALLINT(), nullable=False),
    sa.Column('office_id', sa.SMALLINT(), nullable=False),
    sa.Column('position_id', sa.SMALLINT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('gender', sa.SMALLINT(), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('recommender_id', sa.INTEGER(), nullable=True),
    sa.Column('approver_id', sa.INTEGER(), nullable=True),
    sa.Column('date_email_validated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('email_otp', sa.VARCHAR(length=6), nullable=False),
    sa.Column('email_otp_valid_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('forgot_password_otp', sa.VARCHAR(length=6), nullable=False),
    sa.Column('forgot_password_otp_valid_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('picture_path', sa.TEXT(), nullable=False),
    sa.Column('status', sa.SMALLINT(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.office_id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ),
    sa.ForeignKeyConstraint(['recommender_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.user_type_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('form_applications',
    sa.Column('form_application_id', sa.INTEGER(), nullable=False),
    sa.Column('form_type_id', sa.SMALLINT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('leave_date_started', sa.DATE(), nullable=True),
    sa.Column('leave_date_ended', sa.DATE(), nullable=True),
    sa.Column('leave_number_of_hours', sa.NUMERIC(precision=4, scale=1), nullable=False),
    sa.Column('leave_reason', sa.TEXT(), nullable=False),
    sa.Column('travel_date_started', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('travel_date_ended', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('travel_origin', sa.TEXT(), nullable=False),
    sa.Column('travel_destinations', sa.TEXT(), nullable=False),
    sa.Column('travel_cost', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('travel_reason', sa.TEXT(), nullable=False),
    sa.Column('date_filed', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recommender_user_id', sa.INTEGER(), nullable=False),
    sa.Column('date_recommended', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('approver_user_id', sa.INTEGER(), nullable=False),
    sa.Column('date_approved', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['form_type_id'], ['form_types.form_type_id'], ),
    sa.ForeignKeyConstraint(['recommender_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('form_application_id')
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('date_started', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_stopped', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_expiration', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('time_minute_used', sa.SMALLINT(), nullable=False),
    sa.Column('time_minute_total', sa.SMALLINT(), nullable=False),
    sa.Column('is_active', sa.SMALLINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('user_accesses',
    sa.Column('user_access_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('app_module_action_id', sa.SMALLINT(), nullable=False),
    sa.Column('is_active', sa.SMALLINT(), nullable=False),
    sa.ForeignKeyConstraint(['app_module_action_id'], ['app_module_actions.app_module_action_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_access_id')
    )
    op.create_table('user_type_accesses',
    sa.Column('user_type_access_id', sa.INTEGER(), nullable=False),
    sa.Column('user_type_id', sa.SMALLINT(), nullable=False),
    sa.Column('app_module_action_id', sa.SMALLINT(), nullable=False),
    sa.Column('is_active', sa.SMALLINT(), nullable=False),
    sa.ForeignKeyConstraint(['app_module_action_id'], ['app_module_actions.app_module_action_id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.user_type_id'], ),
    sa.PrimaryKeyConstraint('user_type_access_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_type_accesses')
    op.drop_table('user_accesses')
    op.drop_table('tokens')
    op.drop_table('form_applications')
    op.drop_table('users')
    op.drop_table('app_module_actions')
    op.drop_table('user_types')
    op.drop_table('positions')
    op.drop_table('offices')
    op.drop_table('form_types')
    op.drop_table('app_modules')
    op.drop_table('app_actions')
    # ### end Alembic commands ###
