"""add forgot_password_otp and forgot_password_otp_valid_until fields

Revision ID: 2b86860856e5
Revises: 0fc2f0fe7e7d
Create Date: 2026-01-20 16:57:56.915693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b86860856e5'
down_revision: Union[str, Sequence[str], None] = '0fc2f0fe7e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('forgot_password_otp', sa.VARCHAR(length=6), nullable=True))
    op.add_column('users', sa.Column('forgot_password_otp_valid_until', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'forgot_password_otp_valid_until')
    op.drop_column('users', 'forgot_password_otp')
    # ### end Alembic commands ###
