"""add forgot_password_otp and forgot_password_otp_valid_until fields 2

Revision ID: 44deb94de4ed
Revises: 2b86860856e5
Create Date: 2026-01-20 17:00:39.914083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44deb94de4ed'
down_revision: Union[str, Sequence[str], None] = '2b86860856e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'forgot_password_otp',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'forgot_password_otp',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###
