"""users model new fields date_email_validated and picture_path

Revision ID: 50ed4043e1e4
Revises: 027af728ff54
Create Date: 2026-01-20 09:59:02.203727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ed4043e1e4'
down_revision: Union[str, Sequence[str], None] = '027af728ff54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_email_validated', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('picture_path', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture_path')
    op.drop_column('users', 'date_email_validated')
    # ### end Alembic commands ###
