"""add forgot_password_otp and forgot_password_otp_valid_until fields 3

Revision ID: 8a54f85af6fa
Revises: 44deb94de4ed
Create Date: 2026-01-20 17:01:56.758963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a54f85af6fa'
down_revision: Union[str, Sequence[str], None] = '44deb94de4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'forgot_password_otp',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'forgot_password_otp',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###
