"""new  user table fields recommender_id and approver_id

Revision ID: ff5b05657cb8
Revises: b02e59d5495e
Create Date: 2026-01-28 08:53:20.660955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5b05657cb8'
down_revision: Union[str, Sequence[str], None] = 'b02e59d5495e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recommender_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('approver_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['approver_id'], ['user_id'])
    op.create_foreign_key(None, 'users', 'users', ['recommender_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'approver_id')
    op.drop_column('users', 'recommender_id')
    # ### end Alembic commands ###
